ServerName localhost
Mutex file:/var/lock/apache2 default
PidFile /var/run/apache2/apache2.pid
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User www-data
Group www-data
HostnameLookups Off
ErrorLog /dev/stderr
LogLevel warn
IncludeOptional mods-enabled/mpm_prefork.load
IncludeOptional mods-enabled/mpm_prefork.conf
IncludeOptional mods-enabled/php8.1.load
IncludeOptional mods-enabled/php8.1.conf
IncludeOptional mods-enabled/rewrite.load
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf