ServerName localhost
Listen 80
Mutex file:/var/lock/apache2 default
PidFile /var/run/apache2/apache2.pid
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User www-data
Group www-data
HostnameLookups Off
ErrorLog /dev/stderr
LogLevel warn
IncludeOptional mods-enabled/mpm_prefork.load
IncludeOptional mods-enabled/mpm_prefork.conf
IncludeOptional mods-enabled/mime.load
IncludeOptional mods-enabled/mime.conf
IncludeOptional mods-enabled/dir.load
IncludeOptional mods-enabled/dir.conf
IncludeOptional mods-enabled/php8.1.load
IncludeOptional mods-enabled/php8.1.conf
IncludeOptional mods-enabled/rewrite.load
IncludeOptional mods-enabled/authz_core.load
IncludeOptional mods-enabled/authz_host.load
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf

<Directory /var/www/html>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>